name: GitHub Actions Demo Bootcamp CICD workshop3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
env:
  DUMMY: 2
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      DUMMY: 3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ vars.DUMMY }}, ${{ env.DUMMY }}"